.TH FSX11WM 1 fsx11
.SH NAME
fsx11 \- full screen X11 window manager
.SH SYNOPSIS
.B fsx11
.IR program
.RI [ program-options ]
.SH DESCRIPTION
full screen X11 window manager with less than 100 lines of C89.
.SH USAGE
.TP
.B Mod4\-m
Open
.IR program
in a new, full screen window.
.TP
.B Mod4\-j
Go to next window.
.TP
.B Mod4\-k
Go to previous window.
