.TH FSX11WM 1 fsx11wm
.SH NAME
fsx11wm \- full screen window manager
.SH SYNOPSIS
.B fsx11wm
.IR program
.RI [ program-options ]
.SH DESCRIPTION
full screen window manager with libx11 and less than 100 lines of C89.
.SH USAGE
.TP
.B Mod4\-m
Open
.IR program
in a new, full screen window.
.TP
.B Mod4\-j
Go to next window.
.TP
.B Mod4\-k
Go to previous window.
